// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCieYMNeQxWZudboRVgz98yobJYptfI3TM',
    appId: '1:901763394466:web:fed77b645c2f3e8ad060fb',
    messagingSenderId: '901763394466',
    projectId: 'papyrus-4b385',
    authDomain: 'papyrus-4b385.firebaseapp.com',
    storageBucket: 'papyrus-4b385.appspot.com',
    measurementId: 'G-RDVVXGL1VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoLegWK0c_0xNwEYMLzUHQE59pSEnVk3U',
    appId: '1:901763394466:android:2d7707621c29f725d060fb',
    messagingSenderId: '901763394466',
    projectId: 'papyrus-4b385',
    storageBucket: 'papyrus-4b385.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsqkygIa2UjQd-v1tPorVVfl2BO1U6X6s',
    appId: '1:901763394466:ios:1fba9a4b9bd055cad060fb',
    messagingSenderId: '901763394466',
    projectId: 'papyrus-4b385',
    storageBucket: 'papyrus-4b385.appspot.com',
    iosBundleId: 'com.example.papyrus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsqkygIa2UjQd-v1tPorVVfl2BO1U6X6s',
    appId: '1:901763394466:ios:1fba9a4b9bd055cad060fb',
    messagingSenderId: '901763394466',
    projectId: 'papyrus-4b385',
    storageBucket: 'papyrus-4b385.appspot.com',
    iosBundleId: 'com.example.papyrus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCieYMNeQxWZudboRVgz98yobJYptfI3TM',
    appId: '1:901763394466:web:7ea050b36f595734d060fb',
    messagingSenderId: '901763394466',
    projectId: 'papyrus-4b385',
    authDomain: 'papyrus-4b385.firebaseapp.com',
    storageBucket: 'papyrus-4b385.appspot.com',
    measurementId: 'G-0EQDWB7YL9',
  );
}
